global using Commanda;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using NAudio.Wave;
global using OpenAI;
global using OpenAI.Audio;
global using Services;